import { StyleSheet } from "react-native";

export const GenStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F5F1EE',
    justifyContent: 'center',
    position: 'relative',
  },
  // main
  containerLoggedIn: {
    flex: 1,
    backgroundColor: '#F5F1EE',
    justifyContent: 'flex-start',
    position: 'relative',
  },
  containerContent: {
    height: '87%',
    paddingTop: 20,
  },
  containerFooter: {
    height: '10%',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#E5E0DC',
    borderRadius: 16,
    flexDirection: 'row',
    
  },
  // background circles
  circle1: {
    width: 293,
    height: 293,
    borderRadius: '50%',
    backgroundColor: 'blue',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: -174,
    left: -94.84,
    opacity: 0.7,
  },
  circle2: {
    width: 124.79,
    height: 124.79,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 65.14,
    left: -46.19,
    opacity: 0.7,
    rotation: '-63.14deg',
  },
  circle3: {
    width: 104.61,
    height: 104.61,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 397,
    right: '-15%',
    opacity: 0.7,
    rotation: '-58.22deg',
  },
  circle4: {
    width: 65.81,
    height: 65.81,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 559,
    left: '-8%',
    opacity: 0.7,
    rotation: '-58.22deg',
  },
  // blocks "first page downloading"
  title: {
    fontFamily: 'inter-bold',
    fontSize: 24,
    textAlign: 'left',
    marginBottom: 20,
    marginTop: 20,
  },
  text: {
    fontFamily: 'inter-regular',
    fontSize: 18,
    marginBottom: 20,
  },
  block: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    marginBottom: 10,
    padding: 15,
    borderRadius: 16,
  },
  blockInterests: {
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 16,
    margin: 3,
    paddingLeft: 15,
    paddingRight: 15,
    width: 'auto',
  },
  textBlock: {
    fontFamily: 'inter-regular',
    fontSize: 18,
  },
  buttonLogin: {
    backgroundColor: '#FF9D00',
    fontSize: 18,
    width: '100%',
    padding: 20,
    borderRadius: 100,
    borderColor: '#E27500',
    borderTopWidth: 0, 
    borderRightWidth: 1,
    borderBottomWidth: 3,
    borderLeftWidth: 1,
    marginBottom: 20,
  },
  buttonLoginText: {
    fontFamily: 'inter-bold',
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
  },
  buttonRegister: {
    backgroundColor: 'transparent',
    fontSize: 18,
    width: '100%',
    padding: 20,
    borderRadius: 100,
    borderColor: '#FF9D00',
    borderTopWidth: 1, 
    borderRightWidth: 1,
    borderBottomWidth: 3,
    borderLeftWidth: 1,
    marginBottom: 20,
    marginTop: -10,
  },
  buttonRegisterText: {
    color: '#FF9D00',
    textAlign: 'center',
    fontFamily: 'inter-bold',
    fontSize: 18,
  },
  buttonDisabled: {
    backgroundColor: '#FFCD9D',
    fontSize: 18,
    width: '100%',
    padding: 20,
    borderRadius: 100,
    borderColor: '#FFB472',
    borderTopWidth: 0, 
    borderRightWidth: 1,
    borderBottomWidth: 3,
    borderLeftWidth: 1,
    marginBottom: 20,
  },
  languageLevels: {
    fontSize: 22,
    fontFamily: 'inter-semiBold',
    color: '#E27500',
    marginRight: 20,
  },  
  underTextBlock: {
    fontFamily: 'inter-regular',
    fontSize: 16,
    color: '#716C69',
  },
  IconStyle: {
    marginRight: 10,
  },
  containerInterests: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '90%',
  },
  input: {
    borderRadius: 16,
    paddingLeft: 15,
    paddingRight: 55,
    paddingTop: 20,
    paddingBottom: 20,
    marginBottom: 5,
    marginTop: 10,
    fontFamily: 'inter-regular',
    fontSize: 18,
    color: 'black',
    backgroundColor: 'white',
    transition: 'border-color 2s ease',
  },
  inputFocused: {
    borderColor: '#FF9D00',
    borderWidth: 1,
  },
  inputText: {
    fontFamily: 'inter-bold',
    fontSize: 16,
    color: '#4F4E50',
  },
  textError: {
    fontFamily: 'inter-regular',
    fontSize: 14,
    color: '#EC5050',
    marginBottom: 10,
  },
  circleNamePage1: {
    width: 202,
    height: 202,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 492,
    left: -96,
    opacity: 0.7,
    transform: [{ rotate: '150deg' }],
  },
  circleNamePage2: {
    width: 92,
    height: 92,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 462,
    left: 20,
    opacity: 0.7,
    transform: [{ rotate: '122deg' }],
  },
  circleNamePage3: {
    width: 145,
    height: 145,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 330,
    right: -70,
    opacity: 0.7,
    transform: [{ rotate: '150deg' }],
  },
  circlePassPage1: {
    width: 188,
    height: 188,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 542,
    left: -116,
    opacity: 0.7,
    transform: [{ rotate: '17deg' }],
  },
  circlePassPage2: {
    width: 100,
    height: 100,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 430,
    right: -60,
    opacity: 0.7,
    transform: [{ rotate: '17deg' }],
  },
  // eye button
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  eyeButton: {
    position: 'absolute',
    right: 15,
    top: 25,
    padding: 5,
  },
  eyeIcon: {
    width: 25,
    height: 25,
    tintColor: '#918D8A',
  },
  // circles in the login page
  circleLogin1: {
    width: 112,
    height: 112,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 392,
    left: -56,
    opacity: 0.7,
    transform: [{ rotate: '17deg' }],
  },
  circleLogin2: {
    width: 169,
    height: 169,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 500,
    right: -90,
    opacity: 0.7,
    transform: [{ rotate: '17deg' }],
  },
  // circles in the forgot password page
  circleForgotPassword1: {
    width: 105,
    height: 105,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 332,
    left: -75,
    opacity: 0.7,
  },
  circleForgotPassword2: {
    width: 175,
    height: 175,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 500,
    left: -90,
    opacity: 0.7,
  },
  circleForgotPassword3: {
    width: 161,
    height: 161,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 392,
    right: -50,
    opacity: 0.7,
  },
  circleForgotPassword4: {
    width: 85,
    height: 85,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 530,
    right: -50,
    opacity: 0.7, 
  },
  // circles in the check mail page
  circleCheckMail1: {
    width: 122,
    height: 122,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 520,
    left: -80,
    opacity: 0.7,
  },
  circleCheckMail2: {
    width: 87,
    height: 87,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 250,
    right: -50,
    opacity: 0.7,
  },
  circleCheckMail3: {
    width: 85,
    height: 85,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 500,
    right: -50,
    opacity: 0.7,
  },
  circleCheckMail4: {
    width: 155,
    height: 155,
    borderRadius: '50%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 550,
    right: -80,
    opacity: 0.7,
  },
  imageShow: {
    width: '80%',
    height: 200,
    borderRadius: 16,
    margin: 20,
  }
});